### ISSUE TITLE
Clerk doesn't work?

### ISSUE THREAD

**Issue by EkaanshArora** [VidunderGunder/create-xp-app#1]
Hey, this is an awesome starter! I cloned the project and tried setting it up but looks like Clerk changed the way they handle environment variables. On the dashboard now they prescribe using:
```
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_••••••••••
CLERK_SECRET_KEY=sk_test_••••••••••••
```
Do you plan to update the project to work with more recent versions or clerk? Is this something you'd accept a PR for?

**Comment by VidunderGunder** [comment]
Thanks, and yeah I would absolutely love a PR with a Clerk bump.

The starter is going to be overhauled for my next personal project, but it may take a month or two before I get around to that.

**Comment by EkaanshArora** [comment]
I opened #2 last week, take a look when you get the chance, cheers.
